### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by kkomelin** [sui-foundation/overflow-voting-app#2]
1. I opened the page https://overflow.vote.sui.io/
2. Clicked the "Sign in with Google" button
3. Chose an email from the list of my emails
4. Got this error:

![Screenshot from 2024-06-20 20-38-57](https://github.com/sui-foundation/overflow-voting-app/assets/755066/4e0f848a-b4e7-4f9c-bc74-28f4f1fe3de4)

**Comment by kkomelin** [comment]
The problem is in the GET params of the url: https://overflow.vote.sui.io/?utm_campaign=Sui%20Overflow&utm_medium=email&_hsmi=312496643&utm_content=312496643&utm_source=hs_email

if we remove them, everything gets to normal.

**Comment by dantheman8300** [comment]
This should be fixed in the last commit!

**Comment by kkomelin** [comment]
Will test now and confirm

**Comment by kkomelin** [comment]
Tested. Everything is fine now.

**Comment by dantheman8300** [comment]
Thanks for bringing this to our attention!

**Comment by kkomelin** [comment]
@dantheman8300 Thanks for fixing that quick!
